name: "Auto Label Pull Requests"

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  label-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3

      - name: Auto Label PR
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            const prTitle = pr.title ? pr.title.toLowerCase() : "";
            const prBody = pr.body ? pr.body.toLowerCase() : "";
            const branchName = pr.head && pr.head.ref ? pr.head.ref.toLowerCase() : "";

            const changedFiles = await github.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
            });

            const labelsToAdd = [];

            // Etiquetar según palabras clave en el título de la PR
            if (prTitle.includes("bug")) {
              labelsToAdd.push("bug");
            }
            if (prTitle.includes("feature")) {
              labelsToAdd.push("enhancement");
            }

            // Etiquetar según el nombre de la rama
            if (branchName.includes("task")) {
              labelsToAdd.push("task");
            }
            if (branchName.includes("incidence")) {
              labelsToAdd.push("incidence");
            }

            // Etiquetar según los archivos modificados
            const fileExtensions = changedFiles.data.map(file => file.filename.split('.').pop());
            if (fileExtensions.some(ext => ["html", "js", "css"].includes(ext))) {
              labelsToAdd.push("frontend");
            }
            if (fileExtensions.some(ext => ["py", "java", "rb"].includes(ext))) {
              labelsToAdd.push("backend");
            }

            // Aplicar las etiquetas si hay alguna para añadir
            if (labelsToAdd.length > 0) {
              await github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: labelsToAdd,
              });
            }
